//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.21 at 12:15:47 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
	namespace = "http://ilk.uvt.nl/folia",
	xmlns = {
        @javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI = "http://ilk.uvt.nl/folia"),
    },
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package jargon.model.folia;
